package GUI;

import Logic.Appointment;
import Logic.Child;
import Logic.LogicSystem;
import Logic.Vaccine;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;

public class vNotificaciones extends javax.swing.JFrame {

    LogicSystem sistema;
    Child selectedChild;
    ArrayList<Appointment> consultas;
    ArrayList<Vaccine> vacunas;
    public vNotificaciones(LogicSystem s, Child ch) {
        sistema = s;
        selectedChild = ch;
        initComponents();
        consultas = new ArrayList <Appointment>();
        vacunas = new ArrayList<Vaccine>();
        this.cargarConsultas();
        this.cargarVacunas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloConsultas = new javax.swing.JLabel();
        tituloVacunas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConsultas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVacunas = new javax.swing.JList();
        buttonAceptar = new javax.swing.JButton();
        tituloExpira = new javax.swing.JLabel();
        textExpira = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notificaciones");
        setAlwaysOnTop(true);
        setResizable(false);

        tituloConsultas.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tituloConsultas.setText("Consultas");

        tituloVacunas.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        tituloVacunas.setText("Vacunas");

        listaConsultas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaConsultas);

        listaVacunas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaVacunas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaVacunasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaVacunas);

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        tituloExpira.setText("Expira:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(tituloConsultas)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tituloExpira)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textExpira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloVacunas)
                                .addGap(50, 50, 50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(buttonAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloConsultas)
                    .addComponent(tituloVacunas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloExpira)
                    .addComponent(textExpira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void listaVacunasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaVacunasValueChanged
        //This line prevents double events
        if (!evt.getValueIsAdjusting()) {
        }     
        else{  
            //Obtengo lugar en el ArrayList de Vacunas
            int indexVacuna = listaVacunas.getSelectedIndex();
            //Setteo Fechas en TextFields
            
            if (!selectedChild.getListVaccines().get(indexVacuna).getExpirationMonths().isEmpty()) {
                textExpira.setText(""+selectedChild.getListVaccines().get(indexVacuna).getExpirationMonths().get(0));
            }
            else{
                textExpira.setText(""+selectedChild.getBirthDate());
            }
        }
    }//GEN-LAST:event_listaVacunasValueChanged

    private void cargarConsultas(){
        for (int i = 0; i < selectedChild.getListAppointments().size(); i++) {
            Appointment ap = selectedChild.getListAppointments().get(i);
            if (!ap.getAttended()) {
                if (ap.getAppointmentDate().isAfter(LocalDate.now())) {
                    if (ap.getAppointmentDate().isBefore(LocalDate.now().plus(Period.ofWeeks(2)))) {
                        consultas.add(ap);
                    }
                }
            }
        }
        listaConsultas.setListData(consultas.toArray());
    }
    
    private void cargarVacunas(){
        for (int i = 0; i < selectedChild.getListVaccines().size(); i++) {
            Vaccine vac = selectedChild.getListVaccines().get(i);
            if (vac.getExpirationMonths() != null) {
                if (!vac.getExpirationMonths().isEmpty()) {
                    if (vac.getExpirationMonths().get(0).isAfter(LocalDate.now())) {
                        if (vac.getExpirationMonths().get(0).isBefore(LocalDate.now().plus(Period.ofWeeks(2)))) {
                            vacunas.add(vac);  
                        }                               
                    }
                }
            }                     
        }
        listaVacunas.setListData(vacunas.toArray());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaConsultas;
    private javax.swing.JList listaVacunas;
    private javax.swing.JTextField textExpira;
    private javax.swing.JLabel tituloConsultas;
    private javax.swing.JLabel tituloExpira;
    private javax.swing.JLabel tituloVacunas;
    // End of variables declaration//GEN-END:variables
}
