package GUI;
import Logic.System;
public class vPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vPrincipal
     */
    System sistema;
    public vPrincipal(System s) {
        sistema = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenuPrincipal = new javax.swing.JMenuBar();
        MenuHijos = new javax.swing.JMenu();
        MenuAgregarHijo = new javax.swing.JMenuItem();
        MenuCargarArchivo = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha Medica");

        MenuHijos.setText("Hijos");

        MenuAgregarHijo.setText("Agregar Hijo...");
        MenuAgregarHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgregarHijoActionPerformed(evt);
            }
        });
        MenuHijos.add(MenuAgregarHijo);

        BarraMenuPrincipal.add(MenuHijos);

        MenuCargarArchivo.setText("Cargar Archivo");
        BarraMenuPrincipal.add(MenuCargarArchivo);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        BarraMenuPrincipal.add(MenuSalir);

        setJMenuBar(BarraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        setBounds(0, 0, 791, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void MenuAgregarHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAgregarHijoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuPrincipal;
    private javax.swing.JMenuItem MenuAgregarHijo;
    private javax.swing.JMenu MenuCargarArchivo;
    private javax.swing.JMenu MenuHijos;
    private javax.swing.JMenu MenuSalir;
    // End of variables declaration//GEN-END:variables
}
